# configure auto-configured MultipartConfigElement
multipart:
  location: "${java.io.tmpdir}"
  maxFileSize: 50MB
  maxRequestSize: 50MB

spring:
  mvc:
    favicon:
      enabled: false

logging:
  level.: DEBUG

server:
  port: 9090

com:
  justgifit:
    optimize: true
    gif-location: "${java.io.tmpdir}/gif"

spring.main.allow-bean-definition-overriding: true
